name: Sync to Public Repo

on:
  push:
    branches:
      - krishna-changes

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for a complete mirror

      - name: Push to public repo
        run: |
          git remote add public https://x-access-token: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@github.com/KrishnaMehta123/TestPublicIntegration.git
          git push public krishna-changes:main --force
